dist: xenial
language: php

os:
  - linux

jobs:
  include:
    - php: 7.4.1

  fast_finish: true

before_install:
  - printf "\n" | pecl install imagick
  - curl -sS https://get.symfony.com/cli/installer | sudo bash -s -- --install-dir=/usr/local/bin
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - composer self-update
  - nvm install 12

cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.composer/cache/files

install:
  - php --version
  - composer --version
  - node --version
  - composer install
  - yarn install
  - yarn dev

script:
  - composer check
